### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'type'

### ISSUE THREAD

**Issue by lasxz** [gdlg/panoramic-depth-estimation#2]
This is my command line：

python monodepth_simple.py --image_path ~/007998.png --output_path my_output --checkpoint_path models/panoramic_checkpoints/mixed_warp/model-180000 --input_height 256 --input_width 1024

The following error occurred：

Traceback (most recent call last):
  File "monodepth_simple.py", line 16, in <module>
    import numpy as np
  File "/home/nest/anaconda3/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/nest/anaconda3/lib/python3.5/site-packages/numpy/core/__init__.py", line 57, in <module>
    from . import numerictypes as nt
  File "/home/nest/anaconda3/lib/python3.5/site-packages/numpy/core/numerictypes.py", line 111, in <module>
    from ._type_aliases import (
  File "/home/nest/anaconda3/lib/python3.5/site-packages/numpy/core/_type_aliases.py", line 63, in <module>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
  File "/home/nest/anaconda3/lib/python3.5/site-packages/numpy/core/_type_aliases.py", line 63, in <setcomp>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
AttributeError: 'tuple' object has no attribute 'type'

how to fix it?

**Comment by gdlg** [comment]
It seems to be that your Numpy installation is broken. See numpy/numpy#12775 for potential fix.
